//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Header.cpp
//  Source: Header.idl
//  Generated: Wed Oct  2 09:48:16 2013
//  OpenSplice V6.2.0
//  
//******************************************************************

#include "Header.h"




