//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Point.cpp
//  Source: Point.idl
//  Generated: Wed Oct  2 09:48:22 2013
//  OpenSplice V6.2.0
//  
//******************************************************************

#include "Point.h"




