//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Pose.h
//  Source: Pose.idl
//  Generated: Wed Oct  2 09:48:26 2013
//  OpenSplice V6.2.0
//  
//******************************************************************
#ifndef _POSE_H_
#define _POSE_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "Quaternion.h"
#include "Point.h"
#include "Time.h"
struct Time;
struct Point;
struct Quaternion;
struct Pose;


struct Pose
{
   Point position;
   Quaternion orientation;
};

typedef DDS_DCPSStruct_var < Pose> Pose_var;
typedef Pose&Pose_out;




#endif 
