//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Pose.cpp
//  Source: Pose.idl
//  Generated: Wed Oct  2 09:48:26 2013
//  OpenSplice V6.2.0
//  
//******************************************************************

#include "Pose.h"




