//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: proxyPoseStamped.h
//  Source: proxyPoseStamped.idl
//  Generated: Wed Oct  2 09:48:32 2013
//  OpenSplice V6.2.0
//  
//******************************************************************
#ifndef _PROXYPOSESTAMPED_H_
#define _PROXYPOSESTAMPED_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "Quaternion.h"
#include "Pose.h"
#include "Point.h"
#include "Time.h"
#include "Header.h"
struct Time;
struct Header;
struct Point;
struct Quaternion;
struct Pose;
struct proxyPoseStamped;


struct proxyPoseStamped
{
   Header header;
   Pose pose;
};

typedef DDS_DCPSStruct_var < proxyPoseStamped> proxyPoseStamped_var;
typedef DDS_DCPSStruct_out < proxyPoseStamped> proxyPoseStamped_out;




#endif 
