//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: proxyPoseStampedDcps.cpp
//  Source: proxyPoseStampedDcps.idl
//  Generated: Wed Oct  2 09:48:32 2013
//  OpenSplice V6.2.0
//  
//******************************************************************

#include "proxyPoseStampedDcps.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < proxyPoseStamped, struct proxyPoseStampedSeq_uniq_>;
#endif

const char * proxyPoseStampedTypeSupportInterface::_local_id = "IDL:proxyPoseStampedTypeSupportInterface:1.0";

proxyPoseStampedTypeSupportInterface_ptr proxyPoseStampedTypeSupportInterface::_duplicate (proxyPoseStampedTypeSupportInterface_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean proxyPoseStampedTypeSupportInterface::_local_is_a (const char * _id)
{
   if (strcmp (_id, proxyPoseStampedTypeSupportInterface::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::TypeSupport NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

proxyPoseStampedTypeSupportInterface_ptr proxyPoseStampedTypeSupportInterface::_narrow (DDS::Object_ptr p)
{
   proxyPoseStampedTypeSupportInterface_ptr result = NULL;
   if (p && p->_is_a (proxyPoseStampedTypeSupportInterface::_local_id))
   {
      result = dynamic_cast < proxyPoseStampedTypeSupportInterface_ptr> (p);
      if (result) result->m_count++;
   }
   return result;
}

proxyPoseStampedTypeSupportInterface_ptr proxyPoseStampedTypeSupportInterface::_unchecked_narrow (DDS::Object_ptr p)
{
   proxyPoseStampedTypeSupportInterface_ptr result;
   result = dynamic_cast < proxyPoseStampedTypeSupportInterface_ptr> (p);
   if (result) result->m_count++;
   return result;
}

const char * proxyPoseStampedDataWriter::_local_id = "IDL:proxyPoseStampedDataWriter:1.0";

proxyPoseStampedDataWriter_ptr proxyPoseStampedDataWriter::_duplicate (proxyPoseStampedDataWriter_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean proxyPoseStampedDataWriter::_local_is_a (const char * _id)
{
   if (strcmp (_id, proxyPoseStampedDataWriter::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataWriter NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

proxyPoseStampedDataWriter_ptr proxyPoseStampedDataWriter::_narrow (DDS::Object_ptr p)
{
   proxyPoseStampedDataWriter_ptr result = NULL;
   if (p && p->_is_a (proxyPoseStampedDataWriter::_local_id))
   {
      result = dynamic_cast < proxyPoseStampedDataWriter_ptr> (p);
      if (result) result->m_count++;
   }
   return result;
}

proxyPoseStampedDataWriter_ptr proxyPoseStampedDataWriter::_unchecked_narrow (DDS::Object_ptr p)
{
   proxyPoseStampedDataWriter_ptr result;
   result = dynamic_cast < proxyPoseStampedDataWriter_ptr> (p);
   if (result) result->m_count++;
   return result;
}

const char * proxyPoseStampedDataReader::_local_id = "IDL:proxyPoseStampedDataReader:1.0";

proxyPoseStampedDataReader_ptr proxyPoseStampedDataReader::_duplicate (proxyPoseStampedDataReader_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean proxyPoseStampedDataReader::_local_is_a (const char * _id)
{
   if (strcmp (_id, proxyPoseStampedDataReader::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataReader NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

proxyPoseStampedDataReader_ptr proxyPoseStampedDataReader::_narrow (DDS::Object_ptr p)
{
   proxyPoseStampedDataReader_ptr result = NULL;
   if (p && p->_is_a (proxyPoseStampedDataReader::_local_id))
   {
      result = dynamic_cast < proxyPoseStampedDataReader_ptr> (p);
      if (result) result->m_count++;
   }
   return result;
}

proxyPoseStampedDataReader_ptr proxyPoseStampedDataReader::_unchecked_narrow (DDS::Object_ptr p)
{
   proxyPoseStampedDataReader_ptr result;
   result = dynamic_cast < proxyPoseStampedDataReader_ptr> (p);
   if (result) result->m_count++;
   return result;
}

const char * proxyPoseStampedDataReaderView::_local_id = "IDL:proxyPoseStampedDataReaderView:1.0";

proxyPoseStampedDataReaderView_ptr proxyPoseStampedDataReaderView::_duplicate (proxyPoseStampedDataReaderView_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean proxyPoseStampedDataReaderView::_local_is_a (const char * _id)
{
   if (strcmp (_id, proxyPoseStampedDataReaderView::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataReaderView NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

proxyPoseStampedDataReaderView_ptr proxyPoseStampedDataReaderView::_narrow (DDS::Object_ptr p)
{
   proxyPoseStampedDataReaderView_ptr result = NULL;
   if (p && p->_is_a (proxyPoseStampedDataReaderView::_local_id))
   {
      result = dynamic_cast < proxyPoseStampedDataReaderView_ptr> (p);
      if (result) result->m_count++;
   }
   return result;
}

proxyPoseStampedDataReaderView_ptr proxyPoseStampedDataReaderView::_unchecked_narrow (DDS::Object_ptr p)
{
   proxyPoseStampedDataReaderView_ptr result;
   result = dynamic_cast < proxyPoseStampedDataReaderView_ptr> (p);
   if (result) result->m_count++;
   return result;
}



