//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: proxyPoseStamped.cpp
//  Source: proxyPoseStamped.idl
//  Generated: Wed Oct  2 09:48:32 2013
//  OpenSplice V6.2.0
//  
//******************************************************************

#include "proxyPoseStamped.h"




