//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Quaternion.h
//  Source: Quaternion.idl
//  Generated: Wed Oct  2 09:48:37 2013
//  OpenSplice V6.2.0
//  
//******************************************************************
#ifndef _QUATERNION_H_
#define _QUATERNION_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "Time.h"
struct Time;
struct Quaternion;


struct Quaternion
{
   DDS::Double x;
   DDS::Double y;
   DDS::Double z;
   DDS::Double w;
};

typedef DDS_DCPSStruct_var < Quaternion> Quaternion_var;
typedef Quaternion&Quaternion_out;




#endif 
