//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Quaternion.cpp
//  Source: Quaternion.idl
//  Generated: Wed Oct  2 09:48:37 2013
//  OpenSplice V6.2.0
//  
//******************************************************************

#include "Quaternion.h"




