//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Time.cpp
//  Source: Time.idl
//  Generated: Wed Oct  2 09:48:41 2013
//  OpenSplice V6.2.0
//  
//******************************************************************

#include "Time.h"




