//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Time.h
//  Source: Time.idl
//  Generated: Wed Oct  2 09:48:41 2013
//  OpenSplice V6.2.0
//  
//******************************************************************
#ifndef _TIME_H_
#define _TIME_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
struct Time;


struct Time
{
   DDS::Long sec;
   DDS::Long nsec;
};

typedef DDS_DCPSStruct_var < Time> Time_var;
typedef Time&Time_out;




#endif 
