//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ddsJoy.cpp
//  Source: ddsJoy.idl
//  Generated: Mon Jun 11 14:26:39 2012
//  OpenSplice V5.4.1OSS
//  
//******************************************************************

#include "ddsJoy.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::Long, struct _buttons_seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::Float, struct _axes_seq_uniq_>;
#endif



