//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ddsJoy.h
//  Source: ddsJoy.idl
//  Generated: Mon Jun 11 14:26:39 2012
//  OpenSplice V5.4.1OSS
//  
//******************************************************************
#ifndef _DDSJOY_H_
#define _DDSJOY_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "Time.h"
#include "Header.h"
struct Time;
struct Header;
struct ddsJoy;


struct ddsJoy
{
   struct _axes_seq_uniq_ {};
   typedef DDS_DCPSUFLSeq < DDS::Float, struct _axes_seq_uniq_> _axes_seq;
   typedef DDS_DCPSSequence_var < _axes_seq> _axes_seq_var;
   typedef DDS_DCPSSequence_out < _axes_seq> _axes_seq_out;
   struct _buttons_seq_uniq_ {};
   typedef DDS_DCPSUFLSeq < DDS::Long, struct _buttons_seq_uniq_> _buttons_seq;
   typedef DDS_DCPSSequence_var < _buttons_seq> _buttons_seq_var;
   typedef DDS_DCPSSequence_out < _buttons_seq> _buttons_seq_out;
   Header header;
   _axes_seq axes;
   _buttons_seq buttons;
};

typedef DDS_DCPSStruct_var < ddsJoy> ddsJoy_var;
typedef DDS_DCPSStruct_out < ddsJoy> ddsJoy_out;




#endif 
