//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ddsJoyDcps.cpp
//  Source: ddsJoyDcps.idl
//  Generated: Mon Jun 11 14:26:39 2012
//  OpenSplice V5.4.1OSS
//  
//******************************************************************

#include "ddsJoyDcps.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < ddsJoy, struct ddsJoySeq_uniq_>;
#endif

const char * ddsJoyTypeSupportInterface::_local_id = "IDL:ddsJoyTypeSupportInterface:1.0";

ddsJoyTypeSupportInterface_ptr ddsJoyTypeSupportInterface::_duplicate (ddsJoyTypeSupportInterface_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean ddsJoyTypeSupportInterface::_local_is_a (const char * _id)
{
   if (strcmp (_id, ddsJoyTypeSupportInterface::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::TypeSupport NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

ddsJoyTypeSupportInterface_ptr ddsJoyTypeSupportInterface::_narrow (DDS::Object_ptr p)
{
   ddsJoyTypeSupportInterface_ptr result = NULL;
   if (p && p->_is_a (ddsJoyTypeSupportInterface::_local_id))
   {
      result = dynamic_cast < ddsJoyTypeSupportInterface_ptr> (p);
      result->m_count++;
   }
   return result;
}

ddsJoyTypeSupportInterface_ptr ddsJoyTypeSupportInterface::_unchecked_narrow (DDS::Object_ptr p)
{
   ddsJoyTypeSupportInterface_ptr result;
   result = dynamic_cast < ddsJoyTypeSupportInterface_ptr> (p);
   result->m_count++;
   return result;
}

const char * ddsJoyDataWriter::_local_id = "IDL:ddsJoyDataWriter:1.0";

ddsJoyDataWriter_ptr ddsJoyDataWriter::_duplicate (ddsJoyDataWriter_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean ddsJoyDataWriter::_local_is_a (const char * _id)
{
   if (strcmp (_id, ddsJoyDataWriter::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataWriter NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

ddsJoyDataWriter_ptr ddsJoyDataWriter::_narrow (DDS::Object_ptr p)
{
   ddsJoyDataWriter_ptr result = NULL;
   if (p && p->_is_a (ddsJoyDataWriter::_local_id))
   {
      result = dynamic_cast < ddsJoyDataWriter_ptr> (p);
      result->m_count++;
   }
   return result;
}

ddsJoyDataWriter_ptr ddsJoyDataWriter::_unchecked_narrow (DDS::Object_ptr p)
{
   ddsJoyDataWriter_ptr result;
   result = dynamic_cast < ddsJoyDataWriter_ptr> (p);
   result->m_count++;
   return result;
}

const char * ddsJoyDataReader::_local_id = "IDL:ddsJoyDataReader:1.0";

ddsJoyDataReader_ptr ddsJoyDataReader::_duplicate (ddsJoyDataReader_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean ddsJoyDataReader::_local_is_a (const char * _id)
{
   if (strcmp (_id, ddsJoyDataReader::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataReader NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

ddsJoyDataReader_ptr ddsJoyDataReader::_narrow (DDS::Object_ptr p)
{
   ddsJoyDataReader_ptr result = NULL;
   if (p && p->_is_a (ddsJoyDataReader::_local_id))
   {
      result = dynamic_cast < ddsJoyDataReader_ptr> (p);
      result->m_count++;
   }
   return result;
}

ddsJoyDataReader_ptr ddsJoyDataReader::_unchecked_narrow (DDS::Object_ptr p)
{
   ddsJoyDataReader_ptr result;
   result = dynamic_cast < ddsJoyDataReader_ptr> (p);
   result->m_count++;
   return result;
}

const char * ddsJoyDataReaderView::_local_id = "IDL:ddsJoyDataReaderView:1.0";

ddsJoyDataReaderView_ptr ddsJoyDataReaderView::_duplicate (ddsJoyDataReaderView_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean ddsJoyDataReaderView::_local_is_a (const char * _id)
{
   if (strcmp (_id, ddsJoyDataReaderView::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataReaderView NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

ddsJoyDataReaderView_ptr ddsJoyDataReaderView::_narrow (DDS::Object_ptr p)
{
   ddsJoyDataReaderView_ptr result = NULL;
   if (p && p->_is_a (ddsJoyDataReaderView::_local_id))
   {
      result = dynamic_cast < ddsJoyDataReaderView_ptr> (p);
      result->m_count++;
   }
   return result;
}

ddsJoyDataReaderView_ptr ddsJoyDataReaderView::_unchecked_narrow (DDS::Object_ptr p)
{
   ddsJoyDataReaderView_ptr result;
   result = dynamic_cast < ddsJoyDataReaderView_ptr> (p);
   result->m_count++;
   return result;
}



