//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Header.cpp
//  Source: Header.idl
//  Generated: Mon Jun 11 14:26:46 2012
//  OpenSplice V5.4.1OSS
//  
//******************************************************************

#include "Header.h"




