//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Time.cpp
//  Source: Time.idl
//  Generated: Mon Jun 11 14:24:23 2012
//  OpenSplice V5.4.1OSS
//  
//******************************************************************

#include "Time.h"




