//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Header.cpp
//  Source: Header.idl
//  Generated: Mon Aug  6 04:08:22 2012
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "Header.h"




