//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Point.cpp
//  Source: Point.idl
//  Generated: Fri Jul 27 15:39:23 2012
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "Point.h"




