//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Pose.cpp
//  Source: Pose.idl
//  Generated: Fri Jul 27 15:39:08 2012
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "Pose.h"




