//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: PoseWithCovariance.cpp
//  Source: PoseWithCovariance.idl
//  Generated: Fri Jul 27 15:39:16 2012
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "PoseWithCovariance.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSBFLSeq < DDS::Double, DDS::Double, 36>;
#endif



