//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: PoseWithCovariance.h
//  Source: PoseWithCovariance.idl
//  Generated: Fri Jul 27 15:39:16 2012
//  OpenSplice V5.5.1OSS
//  
//******************************************************************
#ifndef _POSEWITHCOVARIANCE_H_
#define _POSEWITHCOVARIANCE_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "Quaternion.h"
#include "Pose.h"
#include "Point.h"
#include "Time.h"
struct Time;
struct Point;
struct Quaternion;
struct Pose;
struct PoseWithCovariance;


struct PoseWithCovariance
{
   struct _covariance_seq_uniq_ {};
   typedef DDS_DCPSBFLSeq < DDS::Double, DDS::Double, 36> _covariance_seq;
   typedef DDS_DCPSSequence_var < _covariance_seq> _covariance_seq_var;
   typedef DDS_DCPSSequence_out < _covariance_seq> _covariance_seq_out;
   Pose pose;
   _covariance_seq covariance;
};

typedef DDS_DCPSStruct_var < PoseWithCovariance> PoseWithCovariance_var;
typedef DDS_DCPSStruct_out < PoseWithCovariance> PoseWithCovariance_out;




#endif 
