//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: proxyPoseWithCovarianceStamped.cpp
//  Source: proxyPoseWithCovarianceStamped.idl
//  Generated: Thu Jul 26 18:00:33 2012
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "proxyPoseWithCovarianceStamped.h"




