//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: proxyPoseWithCovarianceStamped.h
//  Source: proxyPoseWithCovarianceStamped.idl
//  Generated: Thu Jul 26 18:00:33 2012
//  OpenSplice V5.5.1OSS
//  
//******************************************************************
#ifndef _PROXYPOSEWITHCOVARIANCESTAMPED_H_
#define _PROXYPOSEWITHCOVARIANCESTAMPED_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "Quaternion.h"
#include "Pose.h"
#include "PoseWithCovariance.h"
#include "Point.h"
#include "Time.h"
#include "Header.h"
struct Time;
struct Header;
struct Point;
struct Quaternion;
struct Pose;
struct PoseWithCovariance;
struct proxyPoseWithCovarianceStamped;


struct proxyPoseWithCovarianceStamped
{
   Header header;
   PoseWithCovariance pose;
};

typedef DDS_DCPSStruct_var < proxyPoseWithCovarianceStamped> proxyPoseWithCovarianceStamped_var;
typedef DDS_DCPSStruct_out < proxyPoseWithCovarianceStamped> proxyPoseWithCovarianceStamped_out;




#endif 
