//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Quaternion.cpp
//  Source: Quaternion.idl
//  Generated: Fri Jul 27 15:39:02 2012
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "Quaternion.h"




