//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Time.cpp
//  Source: Time.idl
//  Generated: Thu Jul 26 17:33:32 2012
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "Time.h"




